//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.isagulova.spring_eshop.ws.greeting;

import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.isagulova.spring_eshop.ws.greeting package. 
 * <p>An ObjectFactory allows you to programmatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.isagulova.spring_eshop.ws.greeting
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetGreetingRequest }
     * 
     * @return
     *     the new instance of {@link GetGreetingRequest }
     */
    public GetGreetingRequest createGetGreetingRequest() {
        return new GetGreetingRequest();
    }

    /**
     * Create an instance of {@link GetGreetingResponse }
     * 
     * @return
     *     the new instance of {@link GetGreetingResponse }
     */
    public GetGreetingResponse createGetGreetingResponse() {
        return new GetGreetingResponse();
    }

    /**
     * Create an instance of {@link Greeting }
     * 
     * @return
     *     the new instance of {@link Greeting }
     */
    public Greeting createGreeting() {
        return new Greeting();
    }

}
